Kodi 20 compability for browser launcher (#668)
* Kodi 20 compability for browser launcher

After Updating Kodi from 19 to 20 I received the following exception from plugin.program.browser.launcher:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.program.browser.launcher/default.py", line 23, in <module>
                                                       customPath = xbmc.translatePath(addon.getSetting("customPath"))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

The proposed changes fixes browser.launcher to work with Kodi 20.

Please have a look when time permits. Thank you!

* Update default.py

translatePath import with try block, so we are still compatible with Kodi 18/Leia and up to Kodi20/Nexus